const countryFlags: Record<string, string> = {
  // Russian names
  "США": "🇺🇸",
  "Великобритания": "🇬🇧",
  "Бельгия": "🇧🇪",
  "Германия": "🇩🇪",
  "Чехия": "🇨🇿",
  "Ирландия": "🇮🇪",
  "Япония": "🇯🇵",
  "Мексика": "🇲🇽",
  "Нидерланды": "🇳🇱",
  "Дания": "🇩🇰",
  "Канада": "🇨🇦",
  "Австралия": "🇦🇺",
  "Бразилия": "🇧🇷",
  "Италия": "🇮🇹",
  "Россия": "🇷🇺",
  "Франция": "🇫🇷",
  "Испания": "🇪🇸",
  "Шотландия": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  "Австрия": "🇦🇹",
  "Польша": "🇵🇱",
  "Швеция": "🇸🇪",
  "Норвегия": "🇳🇴",
  "Финляндия": "🇫🇮",
  "Новая Зеландия": "🇳🇿",
  "ЮАР": "🇿🇦",
  "Аргентина": "🇦🇷",
  "Таиланд": "🇹🇭",
  "Южная Корея": "🇰🇷",
  "Сингапур": "🇸🇬",
  "Индия": "🇮🇳",
  "Китай": "🇨🇳",
  // English names (for online search results)
  "USA": "🇺🇸",
  "United States": "🇺🇸",
  "UK": "🇬🇧",
  "United Kingdom": "🇬🇧",
  "England": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  "Belgium": "🇧🇪",
  "Germany": "🇩🇪",
  "Czech Republic": "🇨🇿",
  "Czechia": "🇨🇿",
  "Ireland": "🇮🇪",
  "Japan": "🇯🇵",
  "Mexico": "🇲🇽",
  "Netherlands": "🇳🇱",
  "Denmark": "🇩🇰",
  "Canada": "🇨🇦",
  "Australia": "🇦🇺",
  "Brazil": "🇧🇷",
  "Italy": "🇮🇹",
  "Russia": "🇷🇺",
  "France": "🇫🇷",
  "Spain": "🇪🇸",
  "Scotland": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  "Austria": "🇦🇹",
  "Poland": "🇵🇱",
  "Sweden": "🇸🇪",
  "Norway": "🇳🇴",
  "Finland": "🇫🇮",
  "New Zealand": "🇳🇿",
  "South Africa": "🇿🇦",
  "Argentina": "🇦🇷",
  "Thailand": "🇹🇭",
  "South Korea": "🇰🇷",
  "Singapore": "🇸🇬",
  "India": "🇮🇳",
  "China": "🇨🇳",
  "Portugal": "🇵🇹",
  "Португалия": "🇵🇹",
  "Switzerland": "🇨🇭",
  "Швейцария": "🇨🇭",
};

export function getCountryFlag(country: string): string {
  if (!country) return "";
  return countryFlags[country] || "🌍";
}