import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

function encodeBeerName(name: string): string {
  return encodeURIComponent(name);
}

const beers = [
  {
    name: "Pliny the Elder",
    style: "Double IPA",
    abv: 8.0,
    ibu: 100,
    country: "США",
    brewery: "Russian River Brewing",
    description: "Культовый Double IPA от калифорнийской пивоварни. Мощный хмелевой профиль с нотами сосны, цитрусовых и тропических фруктов. Считается одним из лучших IPA в мире.",
    rating: 4.5,
    ratingCount: 12580,
    totalCheckins: 45200,
    monthlyCheckins: 3200,
    dailyCheckins: 105,
  },
  {
    name: "Guinness Draught",
    style: "Irish Dry Stout",
    abv: 4.2,
    ibu: 45,
    country: "Ирландия",
    brewery: "Guinness & Co.",
    description: "Легендарный ирландский стаут с кремовой текстурой и характерным сухим финишем. Ноты обжаренного ячменя, кофе и тёмного шоколада. Настоящая классика с 1759 года.",
    rating: 3.8,
    ratingCount: 28450,
    totalCheckins: 128000,
    monthlyCheckins: 8900,
    dailyCheckins: 297,
  },
  {
    name: "Weihenstephaner Hefeweissbier",
    style: "Hefeweizen",
    abv: 5.4,
    ibu: 14,
    country: "Германия",
    brewery: "Bayerische Staatsbrauerei Weihenstephan",
    description: "Самое старое пиво в мире, варящееся с 1040 года. Классический баварский пшеничный эль с нотами банана, гвоздики и ванили. Нежная газация и мягкое тело.",
    rating: 4.0,
    ratingCount: 9870,
    totalCheckins: 38600,
    monthlyCheckins: 2100,
    dailyCheckins: 70,
  },
  {
    name: "Pilsner Urquell",
    style: "Czech Pilsner",
    abv: 4.4,
    ibu: 40,
    country: "Чехия",
    brewery: "Plzeňský Prazdroj",
    description: "Оригинальный пильзнер, впервые сваренный в 1842 году. Золотистый цвет, благородная горечь чешского хмеля Saaz и чистый солодовый профиль. Эталон стиля.",
    rating: 3.9,
    ratingCount: 15340,
    totalCheckins: 62100,
    monthlyCheckins: 4300,
    dailyCheckins: 143,
  },
  {
    name: "Budweiser Budvar",
    style: "Czech Pale Lager",
    abv: 5.0,
    ibu: 35,
    country: "Чехия",
    brewery: "Budějovický Budvar",
    description: "Чешский лагер с более чем 120-летней историей. Мягкий солодовый вкус с лёгкой сладостью и сухим финишем. Варится из моравского солода и жатецкого хмеля.",
    rating: 3.5,
    ratingCount: 6780,
    totalCheckins: 24500,
    monthlyCheckins: 1800,
    dailyCheckins: 60,
  },
  {
    name: "Westmalle Tripel",
    style: "Belgian Tripel",
    abv: 9.5,
    ibu: 22,
    country: "Бельгия",
    brewery: "Brouwerij Westmalle",
    description: "Траппистский трипель из аббатства Вестмалле. Золотистый цвет, сложный аромат фруктов, специй и цветочного мёда. Согревающее алкогольное тепло в финише.",
    rating: 4.2,
    ratingCount: 8920,
    totalCheckins: 31400,
    monthlyCheckins: 2200,
    dailyCheckins: 73,
  },
  {
    name: "Chimay Blue Grande Réserve",
    style: "Belgian Dark Strong Ale",
    abv: 11.0,
    ibu: 20,
    country: "Бельгия",
    brewery: "Abbaye de Chimay",
    description: "Тёмный траппистский эль с глубоким и сложным характером. Ноты тёмного сахара, инжира, изюма и лёгкого шоколада. Идеально для выдержки в бутылке.",
    rating: 4.3,
    ratingCount: 7650,
    totalCheckins: 27800,
    monthlyCheckins: 1900,
    dailyCheckins: 63,
  },
  {
    name: "BrewDog Punk IPA",
    style: "IPA",
    abv: 5.6,
    ibu: 40,
    country: "Великобритания",
    brewery: "BrewDog",
    description: "Флагманский IPA шотландской пивоварни. Яркий хмелевой буст с нотами маракуйи, грейпфрута и ананаса. Мягкая горечь с сухим финишем.",
    rating: 3.7,
    ratingCount: 11200,
    totalCheckins: 42300,
    monthlyCheckins: 2900,
    dailyCheckins: 97,
  },
  {
    name: "Sierra Nevada Pale Ale",
    style: "American Pale Ale",
    abv: 5.6,
    ibu: 38,
    country: "США",
    brewery: "Sierra Nevada Brewing Co.",
    description: "Пионер американского крафтового пивоварения с 1980 года. Баланс солодовой основы с хмелевой горечью и цитрусовым ароматом. Настоящая классика жанра.",
    rating: 3.8,
    ratingCount: 14500,
    totalCheckins: 56700,
    monthlyCheckins: 3800,
    dailyCheckins: 127,
  },
  {
    name: "Rochefort 10",
    style: "Belgian Quadrupel",
    abv: 11.3,
    ibu: 25,
    country: "Бельгия",
    brewery: "Brasserie de Rochefort",
    description: "Мощный траппистский эль с богатым body и сложным вкусом. Ноты карамели, тёмных фруктов, шоколада и пряностей. Одно из лучших бельгийских пив.",
    rating: 4.4,
    ratingCount: 8340,
    totalCheckins: 29100,
    monthlyCheckins: 2000,
    dailyCheckins: 67,
  },
  {
    name: "Samuel Adams Boston Lager",
    style: "Vienna Lager",
    abv: 4.9,
    ibu: 30,
    country: "США",
    brewery: "Boston Beer Company",
    description: "Американская классика лагерного пивоварения. Мягкий солодовый вкус с нотами карамели и лёгкой хмелевой горечью. Первое пиво, вернувшее интерес к крафту в США.",
    rating: 3.5,
    ratingCount: 10200,
    totalCheckins: 41800,
    monthlyCheckins: 2700,
    dailyCheckins: 90,
  },
  {
    name: "Corona Extra",
    style: "Pale Lager",
    abv: 4.5,
    ibu: 18,
    country: "Мексика",
    brewery: "Grupo Modelo",
    description: "Самое популярное мексиканское пиво в мире. Лёгкий освежающий вкус с минимальной горечью. Традиционно подаётся с долькой лайма.",
    rating: 3.0,
    ratingCount: 19800,
    totalCheckins: 89200,
    monthlyCheckins: 6100,
    dailyCheckins: 203,
  },
  {
    name: "Heineken Lager",
    style: "Pale Lager",
    abv: 5.0,
    ibu: 23,
    country: "Нидерланды",
    brewery: "Heineken International",
    description: "Международный хит нидерландского пивоварения. Лёгкий хрустящий вкус с характерной травянистой нотой и сухим финишем. One of the most recognised beers globally.",
    rating: 3.2,
    ratingCount: 22300,
    totalCheckins: 98500,
    monthlyCheckins: 7200,
    dailyCheckins: 240,
  },
  {
    name: "Hoegaarden Witbier",
    style: "Belgian Witbier",
    abv: 4.9,
    ibu: 11,
    country: "Бельгия",
    brewery: "Brouwerij Hoegaarden",
    description: "Возрождённый бельгийский белый эль с кориандром и цедрой апельсина. Мутновато-белый цвет, освежающий цитрусовый вкус с пряными нотами. Идеален летом.",
    rating: 3.6,
    ratingCount: 11500,
    totalCheckins: 43200,
    monthlyCheckins: 3000,
    dailyCheckins: 100,
  },
  {
    name: "Founders All Day IPA",
    style: "Session IPA",
    abv: 4.7,
    ibu: 42,
    country: "США",
    brewery: "Founders Brewing Co.",
    description: "Лёгкий сессионный IPA для длительного наслаждения. Яркие цитрусовые и хвойные ноты хмеля с минимальной горечью. Идеальный баланс пьюабельности и вкуса.",
    rating: 3.6,
    ratingCount: 7890,
    totalCheckins: 32100,
    monthlyCheckins: 2200,
    dailyCheckins: 73,
  },
  {
    name: "Stella Artois",
    style: "European Pale Lager",
    abv: 5.0,
    ibu: 24,
    country: "Бельгия",
    brewery: "Anheuser-Busch InBev",
    description: "Бельгийский лагер премиум-класса с 136-летней историей. Чистый хрустящий вкус с лёгкой сладостью и сухим финишем. Подаётся в фирменном бокале-чаше.",
    rating: 3.3,
    ratingCount: 16700,
    totalCheckins: 71400,
    monthlyCheckins: 5100,
    dailyCheckins: 170,
  },
  {
    name: "Belgian White",
    style: "Belgian Witbier",
    abv: 5.2,
    ibu: 13,
    country: "США",
    brewery: "Blue Moon Brewing Co.",
    description: "Американская интерпретация бельгийского витбира с кориандром и апельсиновой цедрой. Нежная текстура и освежающий цитрусовый профиль. Отличное вступление в мир крафта.",
    rating: 3.4,
    ratingCount: 13400,
    totalCheckins: 52800,
    monthlyCheckins: 3600,
    dailyCheckins: 120,
  },
  {
    name: "Hazy Little Thing",
    style: "New England IPA",
    abv: 6.7,
    ibu: 35,
    country: "США",
    brewery: "Sierra Nevada Brewing Co.",
    description: "Мутный NE IPA с взрывным тропическим ароматом. Ноты манго, персика и цитрусовых. Мягкая кремовая текстура с минимальной горечью.",
    rating: 4.0,
    ratingCount: 9100,
    totalCheckins: 35600,
    monthlyCheckins: 2500,
    dailyCheckins: 83,
  },
  {
    name: "Imperial Stout",
    style: "Russian Imperial Stout",
    abv: 14.0,
    ibu: 85,
    country: "США",
    brewery: "Three Floyds Brewing",
    description: "Мощный имперский стаут с невероятной плотностью и сложностью. Ноты тёмного шоколада, эспрессо, табака и тёмных фруктов. Высокое содержание алкоголя едва уловимо.",
    rating: 4.5,
    ratingCount: 5670,
    totalCheckins: 18900,
    monthlyCheckins: 1200,
    dailyCheckins: 40,
  },
  {
    name: "Oberon Ale",
    style: "American Wheat Ale",
    abv: 5.8,
    ibu: 20,
    country: "США",
    brewery: "Bell's Brewery",
    description: "Летний пшеничный эль с яркими фруктовыми нотами. Лёгкое тело с освежающей цитрусовой ноткой. Сезонный релиз, который все ждут с нетерпением.",
    rating: 3.7,
    ratingCount: 8230,
    totalCheckins: 30200,
    monthlyCheckins: 2100,
    dailyCheckins: 70,
  },
  {
    name: "Timmermans Kriek",
    style: "Fruit Lambic",
    abv: 4.0,
    ibu: 0,
    country: "Бельгия",
    brewery: "Brouwerij Timmermans",
    description: "Традиционный бельгийский ламбик с настоящими вишнями. Кисло-сладкий вкус с яркой ягодной кислотностью и нежной фруктовой ароматикой. Наслаждение для гурманов.",
    rating: 3.8,
    ratingCount: 6450,
    totalCheckins: 22100,
    monthlyCheckins: 1500,
    dailyCheckins: 50,
  },
  {
    name: "Dos Equis Lager",
    style: "Vienna Lager",
    abv: 4.2,
    ibu: 19,
    country: "Мексика",
    brewery: "Cuauhtémoc-Moctezuma Brewery",
    description: "Мексиканский лагер с мягким солодовым характером. Лёгкое тело с тонкими карамельными нотами и освежающим финишем. Отличный выбор для жаркого дня.",
    rating: 3.1,
    ratingCount: 8900,
    totalCheckins: 38700,
    monthlyCheckins: 2600,
    dailyCheckins: 87,
  },
  {
    name: "Kölsch",
    style: "Kölsch",
    abv: 4.8,
    ibu: 28,
    country: "Германия",
    brewery: "Reissdorf Kölsch",
    description: "Классический кёльш из Кёльна — единственный город, где можно легально варить этот стиль. Чистый, сухой и освежающий с тонким фруктовым характером. Традиционно подаётся в стакане 0.2л.",
    rating: 3.7,
    ratingCount: 5230,
    totalCheckins: 19800,
    monthlyCheckins: 1300,
    dailyCheckins: 43,
  },
  {
    name: "Bohemian Pilsner",
    style: "Czech Pilsner",
    abv: 4.4,
    ibu: 42,
    country: "Чехия",
    brewery: "Staropramen",
    description: "Пражский пильзнер с насыщенным солодовым вкусом и характерной хмелевой горечью. Золотистый цвет с плотной пеной. Отлично передаёт дух чешского пивоварения.",
    rating: 3.4,
    ratingCount: 7820,
    totalCheckins: 31400,
    monthlyCheckins: 2200,
    dailyCheckins: 73,
  },
  {
    name: "Saison Dupont",
    style: "Saison",
    abv: 6.5,
    ibu: 24,
    country: "Бельгия",
    brewery: "Brasserie Dupont",
    description: "Эталон бельгийского сезона (фермерского эля). Сложный вкус с нотами цитрусовых, перца, земли и солода. Сухой пряный финиш с освежающей кислотностью.",
    rating: 4.1,
    ratingCount: 6890,
    totalCheckins: 24600,
    monthlyCheckins: 1700,
    dailyCheckins: 57,
  },
  {
    name: "Baltika 9",
    style: "Euro Strong Lager",
    abv: 8.0,
    ibu: 18,
    country: "Россия",
    brewery: "Пивоварня Балтика",
    description: "Крепкий лагер от ведущего российского производителя. Плотное солодовое тело с характерной сладостью и тёплым алкогольным финишем. Настоящая классика российского рынка.",
    rating: 2.8,
    ratingCount: 21000,
    totalCheckins: 87300,
    monthlyCheckins: 5800,
    dailyCheckins: 193,
  },
  {
    name: "Жигулёвское",
    style: "Soviet Lager",
    abv: 4.0,
    ibu: 16,
    country: "Россия",
    brewery: "Самарское пивоваренное объединение",
    description: "Культовое советское пиво, чьё название стало нарицательным. Лёгкий солодовый вкус с минимальной горечью и чистым финишем. Часть культурного наследия.",
    rating: 2.5,
    ratingCount: 18900,
    totalCheckins: 75600,
    monthlyCheckins: 4900,
    dailyCheckins: 163,
  },
  {
    name: "Hazy IPA",
    style: "New England IPA",
    abv: 6.2,
    ibu: 30,
    country: "США",
    brewery: "The Alchemist",
    description: "Мутный, сочный и невероятно ароматный NE IPA. Взрывной букет маракуйи, манго и грейпфрута. Мягкая кремовая текстура с нулевой ощущаемой горечью.",
    rating: 4.4,
    ratingCount: 7230,
    totalCheckins: 26800,
    monthlyCheckins: 1850,
    dailyCheckins: 62,
  },
  {
    name: "Tripel Karmeliet",
    style: "Belgian Tripel",
    abv: 8.4,
    ibu: 21,
    country: "Бельгия",
    brewery: "Brouwerij Bosteels",
    description: "Трипель, варенный из трёх видов зерна: пшеницы, овса и ячменя. Мягкий и элегантный с нотами ванили, банана и специй. Долгое тёплое послевкусие.",
    rating: 4.1,
    ratingCount: 7120,
    totalCheckins: 25900,
    monthlyCheckins: 1800,
    dailyCheckins: 60,
  },
  {
    name: "Porter",
    style: "Baltic Porter",
    abv: 8.5,
    ibu: 30,
    country: "Польша",
    brewery: "Żywiec Brewery",
    description: "Мощный балтийский портер с глубоким тёмным цветом. Ноты кофе, тёмного шоколада, карамели и сушёных фруктов. Гладкая текстура с алкогольным теплом.",
    rating: 3.9,
    ratingCount: 5430,
    totalCheckins: 21200,
    monthlyCheckins: 1400,
    dailyCheckins: 47,
  },
  {
    name: "Weissbier",
    style: "Hefeweizen",
    abv: 5.4,
    ibu: 14,
    country: "Германия",
    brewery: "Erdinger Weissbräu",
    description: "Самый известный пшеничный эль Германии. Классические ноты банана и гвоздики с мягкой газацией. Освежающий и питкий, идеален в любую погоду.",
    rating: 3.6,
    ratingCount: 11800,
    totalCheckins: 45200,
    monthlyCheckins: 3100,
    dailyCheckins: 103,
  },
  {
    name: "Double Bastard Ale",
    style: "American Strong Ale",
    abv: 11.2,
    ibu: 95,
    country: "США",
    brewery: "Stone Brewing",
    description: "Агрессивный и мощный крепкий эль от Stone Brewing. Хмелевой удар с нотами сосны, цитрусовых и карамели. Высокая горечь с тёплым алкогольным финишем.",
    rating: 4.0,
    ratingCount: 4890,
    totalCheckins: 16700,
    monthlyCheckins: 1100,
    dailyCheckins: 37,
  },
  {
    name: "Sour Patch",
    style: "American Sour",
    abv: 4.5,
    ibu: 8,
    country: "США",
    brewery: "BrewDog",
    description: "Кислое пиво с яркими ягодными нотами. Насыщенная кислотность балансируется фруктовой сладостью. Необычный и запоминающийся вкус для любителей чего-то нового.",
    rating: 3.5,
    ratingCount: 4120,
    totalCheckins: 15300,
    monthlyCheckins: 1050,
    dailyCheckins: 35,
  },
  {
    name: "Oatmeal Stout",
    style: "Oatmeal Stout",
    abv: 5.9,
    ibv: 32,
    country: "Великобритания",
    brewery: "Samuel Smith Old Brewery",
    description: "Классический овсяный стаут с кремовой текстурой. Ноты кофе, тёмного шоколада и овсяных хлопьев. Гладкое и шелковистое тело с мягкой горечью.",
    rating: 4.0,
    ratingCount: 6780,
    totalCheckins: 23400,
    monthlyCheckins: 1600,
    dailyCheckins: 53,
  },
  {
    name: "Sapporo Premium",
    style: "Japanese Rice Lager",
    abv: 4.9,
    ibu: 16,
    country: "Япония",
    brewery: "Sapporo Breweries",
    description: "Японский рисовый лагер с чистым сухим вкусом. Кристально чистый профиль с минимальной горечью и освежающим финишем. Идеальная пара к суши и сашими.",
    rating: 3.3,
    ratingCount: 9200,
    totalCheckins: 38100,
    monthlyCheckins: 2600,
    dailyCheckins: 87,
  },
  // ========== NEW BEERS (68 added) ==========
  {
    name: "Hitachino Nest White Ale",
    style: "Belgian Witbier",
    abv: 5.0,
    ibu: 15,
    country: "Япония",
    brewery: "Kiuchi Brewery",
    description: "Японская интерпретация бельгийского витбира с кориандром, апельсиновой цедрой и нотами мёда. Нежная мутная текстура и освежающий пряный вкус. Уникальное сочетание европейской традиции и японского подхода.",
    rating: 3.7,
    ratingCount: 4850,
    totalCheckins: 17200,
    monthlyCheckins: 1100,
    dailyCheckins: 37,
  },
  {
    name: "Asahi Super Dry",
    style: "Japanese Dry Lager",
    abv: 5.0,
    ibu: 18,
    country: "Япония",
    brewery: "Asahi Breweries",
    description: "Самое популярное пиво Японии с инновационным сухим профилем. Кристально чистый вкус с минимальной сладостью и мгновенно исчезающим послевкусием. Пионер стиля карасю.",
    rating: 3.2,
    ratingCount: 14200,
    totalCheckins: 58900,
    monthlyCheckins: 3900,
    dailyCheckins: 130,
  },
  {
    name: "Coopers Pale Ale",
    style: "Australian Pale Ale",
    abv: 4.4,
    ibu: 35,
    country: "Австралия",
    brewery: "Coopers Brewery",
    description: "Культовое австралийское нефильтрованное эль-лагер с естественной карбонизацией в бутылке. Фруктовый хмелевой аромат с лёгкой сладостью солода. Национальное достояние Австралии.",
    rating: 3.6,
    ratingCount: 6340,
    totalCheckins: 24800,
    monthlyCheckins: 1650,
    dailyCheckins: 55,
  },
  {
    name: "James Squire One Fifty Lashes",
    style: "Australian Pale Ale",
    abv: 4.2,
    ibu: 28,
    country: "Австралия",
    brewery: "James Squire Brewery",
    description: "Лёгкий австралийский бледный эль с цитрусовыми и тропическими нотами хмеля. Мягкая горечь и освежающий финиш. Идеален для жаркого австралийского лета.",
    rating: 3.4,
    ratingCount: 3210,
    totalCheckins: 13500,
    monthlyCheckins: 890,
    dailyCheckins: 30,
  },
  {
    name: "Coopers Best Extra Stout",
    style: "Extra Stout",
    abv: 6.3,
    ibu: 45,
    country: "Австралия",
    brewery: "Coopers Brewery",
    description: "Плотный австралийский экстра-стаут с насыщенным кофейным и шоколадным характером. Тёмный, почти чёрный цвет с рубиновой подсветкой. Гладкое тело с долгим обжаренным финишем.",
    rating: 3.9,
    ratingCount: 2870,
    totalCheckins: 10200,
    monthlyCheckins: 680,
    dailyCheckins: 23,
  },
  {
    name: "Bohemia Pilsen",
    style: "Czech Pilsner",
    abv: 4.8,
    ibu: 38,
    country: "Бразилия",
    brewery: "Cervejaria Bohemia",
    description: "Бразильская пивоварня с европейскими корнями варит этот пильзнер по чешским традициям. Золотистый цвет, благородная горечь и чистый солодовый вкус. Одно из лучших пив Бразилии.",
    rating: 3.5,
    ratingCount: 4560,
    totalCheckins: 18700,
    monthlyCheckins: 1200,
    dailyCheckins: 40,
  },
  {
    name: "La Fin du Monde",
    style: "Belgian Tripel",
    abv: 9.0,
    ibu: 19,
    country: "Канада",
    brewery: "Unibroue",
    description: "Канадский трипель бельгийского стиля, название которого переводится как «Конец Света». Сложный фруктово-пряный профиль с нотами банана, кориандра и цитрусовых. Мultiple award winner.",
    rating: 4.2,
    ratingCount: 8760,
    totalCheckins: 31500,
    monthlyCheckins: 2100,
    dailyCheckins: 70,
  },
  {
    name: "Molson Export",
    style: "Canadian Ale",
    abv: 5.0,
    ibu: 22,
    country: "Канада",
    brewery: "Molson Coors",
    description: "Классическое канадское пиво с 1903 года. Мягкий солодовый вкус с лёгкой карамельной сладостью и умеренной хмелевой горечью. Часть канадской пивной культуры.",
    rating: 3.3,
    ratingCount: 7890,
    totalCheckins: 32400,
    monthlyCheckins: 2100,
    dailyCheckins: 70,
  },
  {
    name: "Birra Moretti",
    style: "Italian Pale Lager",
    abv: 4.6,
    ibu: 20,
    country: "Италия",
    brewery: "Birra Moretti",
    description: "Итальянский лагер с 1859 года. Сбалансированный солодовый вкус с травянистыми нотами итальянского хмеля. Лёгкое и питкое, идеально к пасте и пицце.",
    rating: 3.2,
    ratingCount: 8900,
    totalCheckins: 36200,
    monthlyCheckins: 2400,
    dailyCheckins: 80,
  },
  {
    name: "Baladin Nora",
    style: "Ancient Ale",
    abv: 6.8,
    ibu: 15,
    country: "Италия",
    brewery: "Birrificio Baladin",
    description: "Уникальное итальянское пиво, вдохновлённое древними египетскими рецептами. Варится с добавлением камута, имбиря и мирры. Экзотический пряный аромат с медовыми нотами.",
    rating: 3.8,
    ratingCount: 2340,
    totalCheckins: 8900,
    monthlyCheckins: 580,
    dailyCheckins: 19,
  },
  {
    name: "Estrella Damm",
    style: "Spanish Pale Lager",
    abv: 4.8,
    ibu: 22,
    country: "Испания",
    brewery: "Estrella Damm",
    description: "Барселонский лагер с 1876 года. Чистый и хрустящий с лёгкой солодовой сладостью и сухим финишем. Символ каталонской пивной культуры и тапас-баров.",
    rating: 3.3,
    ratingCount: 9800,
    totalCheckins: 41200,
    monthlyCheckins: 2700,
    dailyCheckins: 90,
  },
  {
    name: "Moritz",
    style: "Catalan Lager",
    abv: 4.6,
    ibu: 20,
    country: "Испания",
    brewery: "Fàbrica de Cervesa Moritz",
    description: "Легендарная каталонская пивоварня, возрождённая в 2004 году. Мягкий лагер с характерным солодовым профилем и лёгкой цветочной ноткой. Чистый и питкий.",
    rating: 3.5,
    ratingCount: 3120,
    totalCheckins: 12800,
    monthlyCheckins: 840,
    dailyCheckins: 28,
  },
  {
    name: "Mikkeller American Dream",
    style: "American Pale Ale",
    abv: 4.6,
    ibu: 35,
    country: "Дания",
    brewery: "Mikkeller",
    description: "Датский гном-пивовар создаёт классический американский бледный эль с цитрусовым хмелевым профилем. Мягкая горечь с нотами грейпфрута и лайма. Пьюабельный и ароматный.",
    rating: 3.8,
    ratingCount: 4560,
    totalCheckins: 16900,
    monthlyCheckins: 1100,
    dailyCheckins: 37,
  },
  {
    name: "To Øl Mine Mine Mine",
    style: "Brut IPA",
    abv: 6.0,
    ibu: 40,
    country: "Дания",
    brewery: "To Øl",
    description: "Инновационный брют IPA от датских бунтарей пивоварения. Сухой как шампанское, с минеральным финишем и тонкими цитрусовыми нотами. Революция в мире IPA.",
    rating: 3.9,
    ratingCount: 2890,
    totalCheckins: 9800,
    monthlyCheckins: 650,
    dailyCheckins: 22,
  },
  {
    name: "Carlsberg Pilsner",
    style: "European Pale Lager",
    abv: 3.8,
    ibu: 18,
    country: "Дания",
    brewery: "Carlsberg",
    description: "Всемирно известный датский лагер с 1847 года. Лёгкий и освежающий с характерным солодовым вкусом и мягкой хмелевой горечью. Probably the best beer in the world.",
    rating: 3.1,
    ratingCount: 16500,
    totalCheckins: 72300,
    monthlyCheckins: 4800,
    dailyCheckins: 160,
  },
  {
    name: "Nøgne Ø #100",
    style: "American Barleywine",
    abv: 10.5,
    ibu: 85,
    country: "Норвегия",
    brewery: "Nøgne Ø",
    description: "Мощный американский барливайн от ведущей норвежской крафтовой пивоварни. Насыщенный солодовый вкус с нотами карамели, изюма и хмелевой смолы. Высокий алкоголь идеально интегрирован.",
    rating: 4.1,
    ratingCount: 3450,
    totalCheckins: 11200,
    monthlyCheckins: 740,
    dailyCheckins: 25,
  },
  {
    name: "Lervig Rye IPA",
    style: "Rye IPA",
    abv: 7.5,
    ibu: 75,
    country: "Норвегия",
    brewery: "Lervig",
    description: "Норвежский ржаной IPA с мощным хмелевым характером. Рожь придаёт пряный и слегка острый оттенок, балансируя хмелевую горечь. Плотное тело с долгим финишем.",
    rating: 3.9,
    ratingCount: 2780,
    totalCheckins: 9400,
    monthlyCheckins: 620,
    dailyCheckins: 21,
  },
  {
    name: "Omnipollo Anagram",
    style: "New England IPA",
    abv: 6.5,
    ibu: 35,
    country: "Швеция",
    brewery: "Omnipollo",
    description: "Шведский NE IPA с невероятно сочным тропическим ароматом. Ноты манго, маракуйи и персика в мутной кремовой текстуре. Искусство в каждой бутылке.",
    rating: 4.2,
    ratingCount: 3890,
    totalCheckins: 13500,
    monthlyCheckins: 890,
    dailyCheckins: 30,
  },
  {
    name: "Nils Oscar Imperial Stout",
    style: "Russian Imperial Stout",
    abv: 10.5,
    ibu: 80,
    country: "Швеция",
    brewery: "Nils Oscar",
    description: "Шведский имперский стаут с глубоким тёмным характером. Ноты кофе, тёмного шоколада и обжаренного ячменя. Плотное шелковистое тело с тёплым алкогольным финишем.",
    rating: 4.0,
    ratingCount: 2130,
    totalCheckins: 7800,
    monthlyCheckins: 510,
    dailyCheckins: 17,
  },
  {
    name: "Książęce Porter",
    style: "Baltic Porter",
    abv: 10.0,
    ibu: 35,
    country: "Польша",
    brewery: "Tyskie",
    description: "Польский балтийский портер с богатой тёмной палитрой вкуса. Ноты кофе, тёмного шоколада, чернослива и карамели. Гладкая текстура с благородным алкогольным теплом.",
    rating: 3.8,
    ratingCount: 4120,
    totalCheckins: 15800,
    monthlyCheckins: 1050,
    dailyCheckins: 35,
  },
  {
    name: "Tyskie Gronie",
    style: "European Pale Lager",
    abv: 5.0,
    ibu: 25,
    country: "Польша",
    brewery: "Tyskie",
    description: "Самое популярное пиво Польши, варящееся в Тихи с XVII века. Чистый солодовый вкус с лёгкой сладостью и мягкой хмелевой горечью. Польская классика.",
    rating: 3.4,
    ratingCount: 11200,
    totalCheckins: 47800,
    monthlyCheckins: 3100,
    dailyCheckins: 103,
  },
  {
    name: "Starobrno Dark",
    style: "Czech Dark Lager",
    abv: 4.4,
    ibu: 22,
    country: "Чехия",
    brewery: "Starobrno",
    description: "Чешский тёмный лагер из Брно с мягким обжаренным характером. Ноты карамели, шоколада и лёгкого кофе. Плавный и питкий, несмотря на тёмный цвет.",
    rating: 3.5,
    ratingCount: 3890,
    totalCheckins: 14200,
    monthlyCheckins: 940,
    dailyCheckins: 31,
  },
  {
    name: "Kozel Dark",
    style: "Munich Dunkel",
    abv: 3.8,
    ibu: 18,
    country: "Чехия",
    brewery: "Plzeňský Prazdroj",
    description: "Тёмный лагер от знаменитого чешского бренда Kozel. Мягкие карамельно-шоколадные ноты с лёгкой сладостью и гладким финишем. Отличное повседневное тёмное пиво.",
    rating: 3.3,
    ratingCount: 5600,
    totalCheckins: 21300,
    monthlyCheckins: 1400,
    dailyCheckins: 47,
  },
  {
    name: "Murphy's Irish Stout",
    style: "Irish Dry Stout",
    abv: 4.0,
    ibu: 40,
    country: "Ирландия",
    brewery: "Murphy's Brewery",
    description: "Ирландский сухой стаут из Корка с мягким кофейным характером. Более нежный и шоколадный, чем Guinness, с бархатистой текстурой. Альтернатива для ценителей ирландских стаутов.",
    rating: 3.7,
    ratingCount: 5670,
    totalCheckins: 20400,
    monthlyCheckins: 1350,
    dailyCheckins: 45,
  },
  {
    name: "Smithwick's Irish Ale",
    style: "Irish Red Ale",
    abv: 4.5,
    ibu: 20,
    country: "Ирландия",
    brewery: "Smithwick's",
    description: "Классический ирландский красный эль из Килкенни с 1710 года. Мягкие карамельные и хлебные ноты с лёгкой фруктовостью и сухим финишем. Тёплый и приятный.",
    rating: 3.6,
    ratingCount: 6230,
    totalCheckins: 23800,
    monthlyCheckins: 1580,
    dailyCheckins: 53,
  },
  {
    name: "Kronenbourg 1664 Blanc",
    style: "French Witbier",
    abv: 5.0,
    ibu: 12,
    country: "Франция",
    brewery: "Kronenbourg",
    description: "Французский белый эль с нотами цитрусовых и кориандра. Лёгкий и освежающий с фруктовым ароматом и мутноватой текстурой. Популярный выбор для летних вечеров.",
    rating: 3.4,
    ratingCount: 7450,
    totalCheckins: 29600,
    monthlyCheckins: 1950,
    dailyCheckins: 65,
  },
  {
    name: "Jenlain Ambrée",
    style: "Bière de Garde",
    abv: 6.8,
    ibu: 23,
    country: "Франция",
    brewery: "Brasserie Duyck",
    description: "Классическая французская бьер де гард из Северной Франции. Янтарный цвет с нотами карамели, пряностей и лёгкой фруктовой кислотности. Сложный и согревающий.",
    rating: 3.8,
    ratingCount: 2670,
    totalCheckins: 9800,
    monthlyCheckins: 640,
    dailyCheckins: 21,
  },
  {
    name: "Quilmes Cristal",
    style: "Argentine Pale Lager",
    abv: 4.5,
    ibu: 18,
    country: "Аргентина",
    brewery: "Cervecería y Maltería Quilmes",
    description: "Национальное пиво Аргентины с 1888 года. Лёгкий и освежающий лагер с чистым солодовым вкусом. Неразлучный спутник аргентинских асадо и футбола.",
    rating: 3.0,
    ratingCount: 8900,
    totalCheckins: 35600,
    monthlyCheckins: 2350,
    dailyCheckins: 78,
  },
  {
    name: "Epic Armageddon IPA",
    style: "New Zealand IPA",
    abv: 6.6,
    ibu: 70,
    country: "Новая Зеландия",
    brewery: "Epic Brewing Company",
    description: "Флагманский новозеландский IPA с характерным хмелевым профилем Southern Hemisphere. Ноты цитрусовых, тропических фруктов и белого винограда. Мощная горечь с сухим финишем.",
    rating: 4.0,
    ratingCount: 3890,
    totalCheckins: 13800,
    monthlyCheckins: 910,
    dailyCheckins: 30,
  },
  {
    name: "Garage Project Pernicious Weed",
    style: "New Zealand IPA",
    abv: 7.0,
    ibu: 65,
    country: "Новая Зеландия",
    brewery: "Garage Project",
    description: "Новозеландский IPA от культовой веллингтонской пивоварни. Взрывной хмелевой аромат с нотами маракуйи, лайма и хвои. Современный и яркий, как и всё от Garage Project.",
    rating: 4.1,
    ratingCount: 2560,
    totalCheckins: 8900,
    monthlyCheckins: 580,
    dailyCheckins: 19,
  },
  {
    name: "Kingfisher Premium",
    style: "Indian Pale Lager",
    abv: 4.8,
    ibu: 20,
    country: "Индия",
    brewery: "United Breweries",
    description: "Самое популярное пиво Индии, известное далеко за пределами страны. Лёгкий лагер с мягким солодовым вкусом и минимальной горечью. Идеально к индийской кухне.",
    rating: 3.0,
    ratingCount: 10500,
    totalCheckins: 42300,
    monthlyCheckins: 2800,
    dailyCheckins: 93,
  },
  {
    name: "Chang",
    style: "Thai Lager",
    abv: 5.0,
    ibu: 16,
    country: "Таиланд",
    brewery: "Thai Beverage",
    description: "Самое популярное пиво Таиланда с характерной слоновой этикеткой. Лёгкий и освежающий с мягким солодовым вкусом. Незаменимый спутник тайского стрит-фуда.",
    rating: 2.9,
    ratingCount: 7800,
    totalCheckins: 31200,
    monthlyCheckins: 2050,
    dailyCheckins: 68,
  },
  {
    name: "Singha",
    style: "Thai Lager",
    abv: 5.0,
    ibu: 20,
    country: "Таиланд",
    brewery: "Boon Rawd Brewery",
    description: "Первое пиво Таиланда, сваренное в 1933 году. Более выразительный и плотный, чем Chang, с отчётливым хмелевым характером. Премиум-класс тайского пивоварения.",
    rating: 3.2,
    ratingCount: 5670,
    totalCheckins: 22400,
    monthlyCheckins: 1480,
    dailyCheckins: 49,
  },
  {
    name: "Hite",
    style: "Korean Pale Lager",
    abv: 4.5,
    ibu: 18,
    country: "Южная Корея",
    brewery: "HiteJinro",
    description: "Самое продаваемое пиво Южной Кореи. Чистый и лёгкий с refreshing character и минимальной горечью. Популярный выбор для сопровождения корейского барбекю.",
    rating: 3.1,
    ratingCount: 8900,
    totalCheckins: 36500,
    monthlyCheckins: 2400,
    dailyCheckins: 80,
  },
  {
    name: "Kloud",
    style: "Korean Wheat Ale",
    abv: 4.5,
    ibu: 14,
    country: "Южная Корея",
    brewery: "HiteJinro",
    description: "Корейский пшеничный эль с мягким фруктовым характером. Нежная текстура с лёгкими нотами цитрусовых и специй. Освежающий и питкий, отличный вход в мир крафта.",
    rating: 3.4,
    ratingCount: 3450,
    totalCheckins: 12800,
    monthlyCheckins: 840,
    dailyCheckins: 28,
  },
  {
    name: "Bell's Two Hearted Ale",
    style: "American IPA",
    abv: 7.0,
    ibu: 55,
    country: "США",
    brewery: "Bell's Brewery",
    description: "Легендарный американский IPA с центennial хмелем. Мощный цитрусово-хвойной аромат с нотами грейпфрута и сосны. Многократный лучший пиво Америки по версии Zymurgy.",
    rating: 4.3,
    ratingCount: 9870,
    totalCheckins: 37800,
    monthlyCheckins: 2600,
    dailyCheckins: 87,
  },
  {
    name: "Goose Island Bourbon County Stout",
    style: "Barrel-Aged Stout",
    abv: 14.7,
    ibu: 60,
    country: "США",
    brewery: "Goose Island Beer Co.",
    description: "Культовый баррельный стаут, выдержанный в бочках из-под бурбона. Мощный вкус с нотами ванили, бурбона, тёмного шоколада и дуба. Каждый год релиз становится событием.",
    rating: 4.4,
    ratingCount: 6340,
    totalCheckins: 21500,
    monthlyCheckins: 1400,
    dailyCheckins: 47,
  },
  {
    name: "Dogfish Head 90 Minute IPA",
    style: "Imperial IPA",
    abv: 9.0,
    ibu: 90,
    country: "США",
    brewery: "Dogfish Head",
    description: "Имперский IPA, сваренный по технологии непрерывного хмелеварения в течение 90 минут. Мощный хмелевой характер с малярно-смолистыми нотами и мощным телом. Инновация и вкус.",
    rating: 4.1,
    ratingCount: 7120,
    totalCheckins: 26800,
    monthlyCheckins: 1800,
    dailyCheckins: 60,
  },
  {
    name: "Founders KBS",
    style: "Barrel-Aged Stout",
    abv: 11.2,
    ibu: 70,
    country: "США",
    brewery: "Founders Brewing Co.",
    description: "Крепкий стаут, выдержанный в бочках из-под бурбона с добавлением кофе и шоколада. Сложный вкус с нотами кофе, ванили, дуба и тёмного карамельного сахара. Легенда.",
    rating: 4.3,
    ratingCount: 7890,
    totalCheckins: 28400,
    monthlyCheckins: 1900,
    dailyCheckins: 63,
  },
  {
    name: "Deschutes Black Butte Porter",
    style: "American Porter",
    abv: 5.2,
    ibu: 30,
    country: "США",
    brewery: "Deschutes Brewery",
    description: "Американский портер из Орегона с нотами шоколада, кофе и лёгким дымком. Гладкое тело с сбалансированной горечью и тёплым финишем. Флагман пивоварни Deschutes.",
    rating: 4.0,
    ratingCount: 5670,
    totalCheckins: 21300,
    monthlyCheckins: 1400,
    dailyCheckins: 47,
  },
  {
    name: "Lagunitas IPA",
    style: "American IPA",
    abv: 6.2,
    ibu: 51,
    country: "США",
    brewery: "Lagunitas Brewing Company",
    description: "Калифорнийский IPA с выразительным хмелевым характером. Ноты сосны, цитрусовых и тропических фруктов. Мягкая горечь с сухим финишем. Отличный ежедневный IPA.",
    rating: 3.9,
    ratingCount: 10500,
    totalCheckins: 42100,
    monthlyCheckins: 2800,
    dailyCheckins: 93,
  },
  {
    name: "Anchor Steam",
    style: "California Common",
    abv: 4.9,
    ibu: 33,
    country: "США",
    brewery: "Anchor Brewing",
    description: "Единственный настоящий представитель стиля California Common, варящийся с 1896 года. Уникальная комбинация лагерных дрожжей и тёплой ферментации. Ноты карамели и пряных трав.",
    rating: 3.7,
    ratingCount: 4890,
    totalCheckins: 18600,
    monthlyCheckins: 1230,
    dailyCheckins: 41,
  },
  {
    name: "Firestone Walker Union Jack",
    style: "American IPA",
    abv: 6.7,
    ibu: 45,
    country: "США",
    brewery: "Firestone Walker",
    description: "Калифорнийский IPA с чистым и ярким хмелевым профилем. Ноты цитрусовых, лайма и лемонграсса с сухим освежающим финишем. Баланс — ключевое слово.",
    rating: 4.0,
    ratingCount: 6230,
    totalCheckins: 23500,
    monthlyCheckins: 1560,
    dailyCheckins: 52,
  },
  {
    name: "Ballast Point Sculpin",
    style: "American IPA",
    abv: 7.0,
    ibu: 55,
    country: "США",
    brewery: "Ballast Point",
    description: "Сан-диегский IPA с сочным хмелевым ароматом маракуйи, апельсина и ананаса. Мягкая кремовая текстура с балансом между хмелем и солодом. Очень питкий для 7%.",
    rating: 4.1,
    ratingCount: 7450,
    totalCheckins: 27800,
    monthlyCheckins: 1850,
    dailyCheckins: 62,
  },
  {
    name: "Three Floyds Zombie Dust",
    style: "American Pale Ale",
    abv: 6.4,
    ibu: 42,
    country: "США",
    brewery: "Three Floyds Brewing",
    description: "Культовый бледный эль с хмелелем Citra. Невероятно ароматный — маракуйя, лайм и тропические фрукты буквально выпрыгивают из бокала. Пьюабельный и взрывной.",
    rating: 4.3,
    ratingCount: 5340,
    totalCheckins: 18900,
    monthlyCheckins: 1250,
    dailyCheckins: 42,
  },
  {
    name: "Cigar City Jai Alai",
    style: "American IPA",
    abv: 7.2,
    ibu: 65,
    country: "США",
    brewery: "Cigar City Brewing",
    description: "Флоридский IPA с тропическим хмелевым характером. Ноты грейпфрута, апельсина и лайма с заметной хмелевой горечью. Тёплый климат Флориды в каждой бутылке.",
    rating: 4.0,
    ratingCount: 4560,
    totalCheckins: 16700,
    monthlyCheckins: 1100,
    dailyCheckins: 37,
  },
  {
    name: "Toppling Goliath Kentucky Brunch",
    style: "Imperial Stout",
    abv: 12.0,
    ibu: 75,
    country: "США",
    brewery: "Toppling Goliath",
    description: "Мифический имперский стаут с кофе, мёдом и кленовым сиропом. Невероятно сложный вкус с нотами эспрессо, тёмного шоколада и сладкого бурбона. Святой Грааль крафтового пива.",
    rating: 4.6,
    ratingCount: 3120,
    totalCheckins: 9800,
    monthlyCheckins: 640,
    dailyCheckins: 21,
  },
  {
    name: "Tree House Julius",
    style: "New England IPA",
    abv: 6.8,
    ibu: 40,
    country: "США",
    brewery: "Tree House Brewery",
    description: "Небесный NE IPA с хмелем Mosaic. Тропический фруктовый взрыв с нотами манго, маракуйи и цитрусовых. Кремовая мутная текстура с нулевой горечью.",
    rating: 4.5,
    ratingCount: 5890,
    totalCheckins: 19800,
    monthlyCheckins: 1300,
    dailyCheckins: 43,
  },
  {
    name: "Hill Farmstead Abner",
    style: "Double IPA",
    abv: 8.0,
    ibu: 95,
    country: "США",
    brewery: "Hill Farmstead Brewery",
    description: "Фермерский DIPA из Вермонта с комплексным хмелевым профилем. Ноты тропических фруктов, цитрусовых и смолы в мягкой текстуре. Регулярно входит в топ лучших пив мира.",
    rating: 4.5,
    ratingCount: 4230,
    totalCheckins: 14200,
    monthlyCheckins: 940,
    dailyCheckins: 31,
  },
  {
    name: "Russian River Supplication",
    style: "American Sour",
    abv: 7.0,
    ibu: 12,
    country: "США",
    brewery: "Russian River Brewing",
    description: "Кислое пиво, выдержанное в бочках из-под пино нуар с добавлением вишни. Сложная кислотность с нотами вишни, дуба, земли и бальзамического уксуса. Шедевр от Vinnie Cilurzo.",
    rating: 4.4,
    ratingCount: 3560,
    totalCheckins: 11800,
    monthlyCheckins: 780,
    dailyCheckins: 26,
  },
  {
    name: "Allagash White",
    style: "Belgian Witbier",
    abv: 5.1,
    ibu: 13,
    country: "США",
    brewery: "Allagash Brewing",
    description: "Американский витбир в бельгийской традиции с кориандром и цедрой апельсина. Мягкая специй и цитрусовая свежесть в каждом глотке. Один из лучших витбиров вне Бельгии.",
    rating: 3.9,
    ratingCount: 6780,
    totalCheckins: 25400,
    monthlyCheckins: 1680,
    dailyCheckins: 56,
  },
  {
    name: "Brooklyn Brewery Lager",
    style: "Vienna Lager",
    abv: 5.2,
    ibu: 28,
    country: "США",
    brewery: "Brooklyn Brewery",
    description: "Нью-йоркский лагер в венском стиле с карамельными и хлебными нотами. Гладкое тело с сухим финишем и лёгкой хмелевой горечью. Пива, которое объединяет города.",
    rating: 3.6,
    ratingCount: 5340,
    totalCheckins: 21200,
    monthlyCheckins: 1400,
    dailyCheckins: 47,
  },
  {
    name: "Ayinger Celebrator",
    style: "Doppelbock",
    abv: 6.7,
    ibu: 20,
    country: "Германия",
    brewery: "Ayinger Privatbrauerei",
    description: "Классический немецкий двойной бок с характерным солодовым характером. Ноты карамели, тёмного хлеба, шоколада и сушёных фруктов. Икона баварского пивоварения.",
    rating: 4.2,
    ratingCount: 6230,
    totalCheckins: 23800,
    monthlyCheckins: 1580,
    dailyCheckins: 53,
  },
  {
    name: "Paulaner Salvator",
    style: "Doppelbock",
    abv: 7.9,
    ibu: 22,
    country: "Германия",
    brewery: "Paulaner",
    description: "Оригинальный доппельбок, прародитель стиля с 1634 года. Плотный солодовый характер с нотами карамели, изюма и мёда. Тёплое алкогольное послевкусие. Salvator ducit.",
    rating: 4.0,
    ratingCount: 5670,
    totalCheckins: 21500,
    monthlyCheckins: 1420,
    dailyCheckins: 47,
  },
  {
    name: "Schneider Weisse Aventinus",
    style: "Weizenbock",
    abv: 8.2,
    ibu: 18,
    country: "Германия",
    brewery: "Schneider Weisse",
    description: "Тёмный пшеничный бок от легендарной пивоварни Шнайдер. Ноты банана, гвоздики, изюма и тёмного хлеба в мощном теле. Один из лучших пшеничных элей в мире.",
    rating: 4.3,
    ratingCount: 5340,
    totalCheckins: 19800,
    monthlyCheckins: 1310,
    dailyCheckins: 44,
  },
  {
    name: "Franziskaner Dunkel",
    style: "Dunkelweizen",
    abv: 5.5,
    ibu: 13,
    country: "Германия",
    brewery: "Franziskaner",
    description: "Тёмный пшеничный эль из Мюнхена с мягким бананово-гвоздичным характером. Ноты шоколада и карамели добавляют глубину классическому вайсбир-профилю. Нежный и питкий.",
    rating: 3.8,
    ratingCount: 4120,
    totalCheckins: 15600,
    monthlyCheckins: 1030,
    dailyCheckins: 34,
  },
  {
    name: "Schönramer Dunkel",
    style: "Munich Dunkel",
    abv: 4.9,
    ibu: 22,
    country: "Германия",
    brewery: "Privatbrauerei Schönram",
    description: "Баварский мюнхенский дункель с богатым обжаренным солодовым характером. Ноты хлебной корки, карамели и лёгкого шоколада. Гладкое тело с чистым сухим финишем.",
    rating: 3.9,
    ratingCount: 2890,
    totalCheckins: 10800,
    monthlyCheckins: 710,
    dailyCheckins: 24,
  },
  {
    name: "Köstritzer Schwarzbier",
    style: "Schwarzbier",
    abv: 4.8,
    ibu: 28,
    country: "Германия",
    brewery: "Köstritzer",
    description: "Классический немецкий чёрный лагер из Тюрингии с 1543 года. Обжаренный солодовый характер с нотами кофе и шоколада, но лёгкий и питкий. Чёрный цвет не обманывает.",
    rating: 3.8,
    ratingCount: 5670,
    totalCheckins: 22400,
    monthlyCheckins: 1480,
    dailyCheckins: 49,
  },
  {
    name: "Uerige Obergäriges Altbier",
    style: "Altbier",
    abv: 4.6,
    ibu: 38,
    country: "Германия",
    brewery: "Uerige",
    description: "Культовый альтбир из Дюссельдорфа с 1862 года. Топовой ферментации, но лагерный характер. Мощная хмелевая горечь с солодовой основой и сухим финишем. Легенда Дюссельдорфа.",
    rating: 3.9,
    ratingCount: 3890,
    totalCheckins: 14500,
    monthlyCheckins: 960,
    dailyCheckins: 32,
  },
  {
    name: "Bayerischer Bahnhof Berliner Weisse",
    style: "Berliner Weisse",
    abv: 3.5,
    ibu: 5,
    country: "Германия",
    brewery: "Bayerischer Bahnhof",
    description: "Традиционный берлинер вайсе с освежающей молочной кислотностью. Кислый и лёгкий, традиционно подаётся с сиропом вальдмайстер или химбеер. Berliner Kindl классики.",
    rating: 3.5,
    ratingCount: 3120,
    totalCheckins: 11800,
    monthlyCheckins: 780,
    dailyCheckins: 26,
  },
  {
    name: "Göller Gose",
    style: "Gose",
    abv: 4.6,
    ibu: 8,
    country: "Германия",
    brewery: "Brauhaus Göller",
    description: "Традиционная лейпцигская гозе с лёгкой кислинкой и отчётливой солоноватостью. Ноты кориандра и цитрусовых в освежающем теле. Возрождённая классика немецкого пивоварения.",
    rating: 3.6,
    ratingCount: 2560,
    totalCheckins: 9400,
    monthlyCheckins: 620,
    dailyCheckins: 21,
  },
  {
    name: "Schneider Tap 7 My-Xyus",
    style: "Hefeweizen",
    abv: 5.4,
    ibu: 15,
    country: "Германия",
    brewery: "Schneider Weisse",
    description: "Хрустящий пшеничный эль с яркими нотами банана и гвоздики. Чистый и освежающий с шелковистой текстурой и плотной белой пеной. Современная классика от Шнайдер.",
    rating: 4.0,
    ratingCount: 3780,
    totalCheckins: 14200,
    monthlyCheckins: 940,
    dailyCheckins: 31,
  },
  {
    name: "Rodenbach Grand Cru",
    style: "Flanders Red Ale",
    abv: 6.0,
    ibu: 0,
    country: "Бельгия",
    brewery: "Brouwerij Rodenbach",
    description: "Фламандский красный эль, выдержанный в дубовых бочках до двух лет. Сложная кислотность с нотами вишни, граната, дуба и бальзамического уксуса. Фландрийское бургундское пиво.",
    rating: 4.2,
    ratingCount: 4560,
    totalCheckins: 15800,
    monthlyCheckins: 1050,
    dailyCheckins: 35,
  },
  {
    name: "Liefmans Oud Bruin",
    style: "Oud Bruin",
    abv: 6.0,
    ibu: 0,
    country: "Бельгия",
    brewery: "Brouwerij Liefmans",
    description: "Бельгийский oud bruin с кисло-сладким характером и фруктовыми нотами. Ноты вишни, сливы и карамели в гладком теле. Уникальный вкус, который нужно попробовать.",
    rating: 3.7,
    ratingCount: 3120,
    totalCheckins: 11200,
    monthlyCheckins: 740,
    dailyCheckins: 25,
  },
  {
    name: "Duvel",
    style: "Belgian Strong Golden Ale",
    abv: 8.5,
    ibu: 32,
    country: "Бельгия",
    brewery: "Duvel Moortgat",
    description: "Легендарный бельгийский крепкий золотой эль с 1923 года. Золотистый цвет, сложный фруктово-пряный аромат и сухой финиш. Алкоголь практически не ощущается. Шедевр.",
    rating: 4.3,
    ratingCount: 9870,
    totalCheckins: 38200,
    monthlyCheckins: 2540,
    dailyCheckins: 85,
  },
  {
    name: "Orval",
    style: "Belgian Pale Ale",
    abv: 6.9,
    ibu: 28,
    country: "Бельгия",
    brewery: "Abbaye Notre-Dame d'Orval",
    description: "Траппистский эль с уникальным сухим хмелевым характером. Дикие дрожжи Бреттаномицес дают характерную фермерскую нотку. Сложный, элегантный и непредсказуемый.",
    rating: 4.2,
    ratingCount: 7120,
    totalCheckins: 26800,
    monthlyCheckins: 1780,
    dailyCheckins: 59,
  },
  {
    name: "Fuller's ESB",
    style: "ESB",
    abv: 5.5,
    ibu: 28,
    country: "Великобритания",
    brewery: "Fuller's Brewery",
    description: "Классический британский ESB — Extra Special Bitter из Лондона. Мощный солодовый характер с нотами карамели, бисквита и фруктового английского хмеля. Настоящая английская классика.",
    rating: 4.0,
    ratingCount: 5340,
    totalCheckins: 20200,
    monthlyCheckins: 1340,
    dailyCheckins: 45,
  },
  {
    name: "Belhaven Wee Heavy",
    style: "Scotch Wee Heavy",
    abv: 6.5,
    ibu: 25,
    country: "Великобритания",
    brewery: "Belhaven",
    description: "Шотландский wee heavy с богатым солодовым характером. Ноты карамели, тёмного сахара, лёгкого торфяного дыма и сушёных фруктов. Тёплое и согревающее.",
    rating: 3.8,
    ratingCount: 3780,
    totalCheckins: 14200,
    monthlyCheckins: 940,
    dailyCheckins: 31,
  },
  {
    name: "Harvey's Sussex Best Bitter",
    style: "English Bitter",
    abv: 4.0,
    ibu: 25,
    country: "Великобритания",
    brewery: "Harvey's",
    description: "Классический английский биттер из Сассекса. Нежный солодовый вкус с фруктовыми нотами и умеренной хмелевой горечью. Пьётся легко, идеально для паба.",
    rating: 3.8,
    ratingCount: 3120,
    totalCheckins: 12400,
    monthlyCheckins: 820,
    dailyCheckins: 27,
  },
  {
    name: "Newcastle Brown Ale",
    style: "English Brown Ale",
    abv: 4.7,
    ibu: 20,
    country: "Великобритания",
    brewery: "Newcastle Brewery",
    description: "Знаменитый английский коричневый эль с северо-востока Англии. Мягкие ноты карамели, ореха и хлеба с лёгкой фруктовостью. Национальное достояние Англии.",
    rating: 3.4,
    ratingCount: 7450,
    totalCheckins: 29800,
    monthlyCheckins: 1980,
    dailyCheckins: 66,
  },
  {
    name: "Mikkeller Beer Geek Brunch",
    style: "Oatmeal Stout",
    abv: 10.9,
    ibu: 65,
    country: "Дания",
    brewery: "Mikkeller",
    description: "Датский овсяный стаут с добавлением кофе Geisha. Невероятно мощный вкус с нотами эспрессо, тёмного шоколада и дуба. Кофейный шедевр от Микаелла Бьергсо.",
    rating: 4.3,
    ratingCount: 3450,
    totalCheckins: 11200,
    monthlyCheckins: 740,
    dailyCheckins: 25,
  },
  {
    name: "Delirium Tremens",
    style: "Belgian Strong Golden Ale",
    abv: 8.5,
    ibu: 26,
    country: "Бельгия",
    brewery: "Brouwerij Huyghe",
    description: "Бельгийский крепкий эль с культовой розовой слоновой бутылкой. Сложный фруктово-пряный характер с нотами кориандра и цитрусовых. Лёгкая пряность в финише.",
    rating: 4.0,
    ratingCount: 8900,
    totalCheckins: 34500,
    monthlyCheckins: 2290,
    dailyCheckins: 76,
  },
  {
    name: "Affligem Blond",
    style: "Belgian Blond Ale",
    abv: 6.8,
    ibu: 20,
    country: "Бельгия",
    brewery: "Brouwerij Affligem",
    description: "Бельгийский блонд эль с аббатскими традициями. Фруктовый аромат с нотами груши и специй. Мягкое тело с сухим хмелевым финишем и лёгким алкогольным теплом.",
    rating: 3.7,
    ratingCount: 4780,
    totalCheckins: 18500,
    monthlyCheckins: 1230,
    dailyCheckins: 41,
  },
];

// Fix the typo
const correctedBeers = beers.map((b) => {
  const beer = { ...b };
  if ('ibv' in beer) {
    (beer as Record<string, unknown>).ibu = (beer as Record<string, unknown>).ibv;
    delete (beer as Record<string, unknown>).ibv;
  }
  return beer;
});

const reviewAuthors = [
  "Александр К.",
  "Мария П.",
  "Дмитрий С.",
  "Елена В.",
  "Иван Р.",
  "Ольга Н.",
  "Сергей М.",
  "Анна Т.",
  "Павел Л.",
  "Наталья Д.",
  "Андрей Б.",
  "Татьяна Ф.",
  "Максим Ж.",
  "Юлия Ш.",
  "Роман А.",
  "Виктор Е.",
  "Константин Г.",
  "Алексей О.",
  "Светлана И.",
  "Денис К.",
  "Игорь В.",
  "Оксана Л.",
  "Николай П.",
  "Валерия М.",
];

function generateReviews(beerName: string, style: string): Array<{
  author: string;
  rating: number;
  comment: string;
}> {
  const reviewsByStyle: Record<string, Array<{ rating: number; comment: string }>> = {
    "Double IPA": [
      { rating: 5.0, comment: "Невероятный хмелевой взрыв! Сосна и грейпфрут просто поражают. Лучший DIPA, который я пробовал." },
      { rating: 4.5, comment: "Мощный и комплексный. Хмелевой профиль на высоте, но алкоголь всё же чувствуется." },
      { rating: 4.0, comment: "Отличное пиво, но немного перебор с горечью для моего вкуса. Аромат — шикарный." },
      { rating: 4.5, comment: "Классика жанра! Пью каждый раз, когда нахожу в магазине. Никогда не разочаровывает." },
    ],
    "Irish Dry Stout": [
      { rating: 4.0, comment: "Кремовая текстура и кофейные ноты — то, что нужно холодным вечером. Классика." },
      { rating: 3.5, comment: "Хороший стаут, но в банке не то же самое что на разливе из кега." },
      { rating: 4.0, comment: "Подаётся с виджетом, пена как у капучино. Вкус стабильно хороший." },
      { rating: 3.5, comment: "Для меня слишком лёгкий, ожидал более насыщенный вкус. Но это классика." },
      { rating: 4.0, comment: "Обожаю этот стаут с устрицами! Идеальное сочетание. Плотная пена и сухой финиш." },
    ],
    "Hefeweizen": [
      { rating: 4.5, comment: "Банан и гвоздика — идеальный баланс! Самый правильный вайсбир, который я пробовал." },
      { rating: 4.0, comment: "Мутный, фруктовый, освежающий. Точно так должен выглядеть классический вайсбир." },
      { rating: 4.0, comment: "Летом просто спасение. Пьётся легко, газация мягкая, аромат потрясающий." },
      { rating: 3.5, comment: "Немного пресноват для меня, но стиль соблюдён идеально." },
    ],
    "Czech Pilsner": [
      { rating: 4.0, comment: "Эталон пильзнера! Чистый солодовый вкус и благородная горечь Saaz." },
      { rating: 4.5, comment: "Пил в Праге на разливе — небо и земля по сравнению с тем, что продаётся у нас. Но и так отлично!" },
      { rating: 3.5, comment: "Хорошее пиво, но для меня чуть слишком горький. Чистый и свежий." },
      { rating: 4.0, comment: "Изумрудный цвет и плотная пена. Вкус — именно то, что я жду от чешского пива." },
      { rating: 3.5, comment: "Классика, но есть и получше. Хмелевой профиль на высоте." },
    ],
    "Belgian Tripel": [
      { rating: 5.0, comment: "Великолепный трипель! Сложный, элегантный, согревающий. Каждый глоток — открытие." },
      { rating: 4.5, comment: "Специи, фрукты, мёд — невероятный букет. Алкоголь отлично замаскирован." },
      { rating: 4.0, comment: "Мощный и сложный, но мне чуть больше нравится Chimay Blue." },
      { rating: 4.5, comment: "Траппистское качество на лицо. Один из лучших трипелей мира." },
    ],
    "Belgian Dark Strong Ale": [
      { rating: 5.0, comment: "Магия в бутылке! Тёмные фрукты, шоколад, инжир... Этот вкус невозможно забыть." },
      { rating: 4.5, comment: "Потрясающая сложность. Выдержанная версия ещё лучше — с годами становится мягче." },
      { rating: 4.5, comment: "Одно из лучших бельгийских пив. Тёплое алкогольное послевкусие — просто мечта." },
      { rating: 4.0, comment: "Отлично, но 11% чувствуется. Пить нужно медленно и с уважением." },
    ],
    "IPA": [
      { rating: 4.0, comment: "Яркий хмелевой аромат, но вкус немного разбавленный. Хорошо для знакомства с IPA." },
      { rating: 3.5, comment: "Попсовый IPA, но ничего плохого не скажу. Маракуйя и цитрусы налицо." },
      { rating: 4.0, comment: "Пьётся легко для 5.6%. Хмелевой профиль приятный, не перебивает." },
      { rating: 3.5, comment: "Нормальный IPA для повседневного употребления. Есть и поинтереснее варианты." },
    ],
    "American Pale Ale": [
      { rating: 4.0, comment: "Классика американского крафта! Солод и хмель в идеальном балансе." },
      { rating: 4.0, comment: "Стабильное качество годами. Цитрусовый хмель и чистый финиш." },
      { rating: 3.5, comment: "Хороший APA, но в эпоху NE IPA уже кажется немного простоватым." },
      { rating: 4.5, comment: "Пионер, который определил стиль. Уважение и отличное пиво!" },
    ],
    "Belgian Quadrupel": [
      { rating: 5.0, comment: "Шедевр траппистского пивоварения! Сложный, мощный, невероятно вкусный." },
      { rating: 4.5, comment: "11.3%, но алкоголь почти не ощущается. Тёмные фрукты и карамель — божественно." },
      { rating: 4.5, comment: "Лучший квадрюпель из тех, что я пробовал. Каждая бутылка — праздник." },
      { rating: 4.0, comment: "Очень хорошее пиво, но для меня чуть слишком сладкое. Впрочем, это стиль." },
    ],
    "Vienna Lager": [
      { rating: 3.5, comment: "Неплохой лагер с карамельными нотами. Хорошая альтернатива масс-маркету." },
      { rating: 3.0, comment: "Ожидания были выше. Пьётся нормально, но ничего выдающегося." },
      { rating: 3.5, comment: "Тёплый солодовый характер приятен. Хорошо с бургерами." },
    ],
    "Pale Lager": [
      { rating: 3.0, comment: "Обычное пиво для вечеринок. С лаймом получше." },
      { rating: 3.0, comment: "Лёгкое и ненавязчивое. Не ждёшь ничего особенного, но и не разочаровывает." },
      { rating: 2.5, comment: "Для меня слишком водянистое. Но в жару на пляже — норм." },
      { rating: 3.0, comment: "Классика мексиканского пива. С тако и лаймом заходит отлично." },
    ],
    "European Pale Lager": [
      { rating: 3.5, comment: "Чистый и хрустящий, как и должно быть. Хорош для больших компаний." },
      { rating: 3.0, comment: "Обычное европейское пиво. Ничего особенного, но пить можно." },
      { rating: 3.5, comment: "В бокале из-под Стеллы вообще другое дело! Классная подача." },
    ],
    "Belgian Witbier": [
      { rating: 4.0, comment: "Освежающий цитрусовый вкус с пряными нотами. Лето в бокале!" },
      { rating: 3.5, comment: "Нравится кориандр и апельсин. Мутноватый вид добавляет шарма." },
      { rating: 4.0, comment: "Идеально для жаркого дня. Лёгкое, ароматное, питкое." },
      { rating: 3.5, comment: "Хороший витбир, но Хугарден всё-таки лучше." },
    ],
    "Session IPA": [
      { rating: 4.0, comment: "Отличный сессионный IPA! Цитрусы и хвоя, но при этом можно выпить несколько." },
      { rating: 3.5, comment: "Хороший компромисс между вкусом и пьюабельностью. Хмелевой профиль приятный." },
      { rating: 3.5, comment: "Для 4.7% довольно выразительный. Отличный вариант на весь вечер." },
    ],
    "New England IPA": [
      { rating: 5.0, comment: "Манго, маракуйя, персик — это не пиво, это фруктовый сок! Обожаю!" },
      { rating: 4.5, comment: "Невероятно ароматный и мягкий. Тот самый стиль, который изменил моё отношение к пиву." },
      { rating: 4.0, comment: "Мутный и сочный, как и должно быть. Хотел чуть больше горечи в финише." },
      { rating: 4.5, comment: "Hazy Little Thing не разочаровывает. Всегда свежий и ароматный." },
    ],
    "Russian Imperial Stout": [
      { rating: 5.0, comment: "Монстр! 14% но пьётся как десерт. Шоколад, кофе, тёмные фрукты..." },
      { rating: 4.5, comment: "Самый мощный стаут, который я пробовал. Выдержанная версия — вообще космос." },
      { rating: 4.5, comment: "Плотный, сложный, тёплый. Идеально для зимних вечеров. Шедевр!" },
      { rating: 4.0, comment: "Отличное пиво, но 14% — это серьёзно. Одной бутылки хватает с запасом." },
    ],
    "American Wheat Ale": [
      { rating: 4.0, comment: "Летний хит! Фруктовый и лёгкий, пьётся сам собой." },
      { rating: 3.5, comment: "Хорошо, но есть получше в этом стиле. Всё же Oberon — это классика лета." },
      { rating: 3.5, comment: "Освежающий, но для пшеничного мне не хватает классических банановых нот." },
    ],
    "Fruit Lambic": [
      { rating: 4.0, comment: "Вишнёвый ламбик — это любовь! Кислинка и ягоды в идеальном балансе." },
      { rating: 4.5, comment: "Настоящий бельгийский ламбик с настоящими вишнями. Рай для гурмана!" },
      { rating: 3.5, comment: "Для непривычного вкус может показаться странным, но это стоит попробовать." },
      { rating: 4.0, comment: "Кисло-сладкий баланс отличный. Хорошо как аперитив или десертное пиво." },
    ],
    "Kölsch": [
      { rating: 4.0, comment: "Чистый, сухой, освежающий. В Кёльне это пьют литрами — и я понимаю почему!" },
      { rating: 3.5, comment: "Хороший немецкий лагер-эль гибрид. Пьётся легко и с удовольствием." },
      { rating: 4.0, comment: "Рейсдорф — правильный кёльш. Чистый профиль, никаких лишних нот." },
    ],
    "Saison": [
      { rating: 4.5, comment: "Эталон сезона! Пряный, сухой, сложный. Каждый глоток раскрывает новые грани." },
      { rating: 4.0, comment: "Перец, цитрусы, лёгкая кислотность — очень интересный и многогранный вкус." },
      { rating: 4.5, comment: "Дюпон делает лучшие сезоны в мире. Это неоспоримо." },
      { rating: 4.0, comment: "Сложное пиво, которое не каждому понравится. Но я в восторге!" },
    ],
    "Euro Strong Lager": [
      { rating: 3.0, comment: "Крепкий и сладковатый. Для своих 8% пьётся легко, но это не крафт." },
      { rating: 2.5, comment: "Классика студенческих вечеринок. Не ждёшь качества, но задача выполняет." },
      { rating: 3.0, comment: "Тёплый и солодовый. Лучше многих дешёвых креплёных вариантов." },
      { rating: 2.5, comment: "Балтика 9 — это как ритуал посвящения. Все через это проходили." },
    ],
    "Soviet Lager": [
      { rating: 2.5, comment: "Ностальгия! Вкус детства, если можно так сказать. Простое пиво без претензий." },
      { rating: 2.5, comment: "Жигулёвское есть Жигулёвское. Ничего особенного, но дёшево и сердито." },
      { rating: 3.0, comment: "За свою цену — нормально. Лёгкий и ненавязчивый." },
      { rating: 2.5, comment: "Культовое пиво, но по качеству — обычной лагер. Ностальгия правит бал." },
    ],
    "American Strong Ale": [
      { rating: 4.0, comment: "Мощный и агрессивный, как и обещает название! Хмель бьёт в нос." },
      { rating: 4.5, comment: "Stone делает отличное пиво, а Double Bastard — один из их лучших." },
      { rating: 3.5, comment: "11.2% и 95 IBU — это серьёзно. Не для слабонервных, но мне нравится." },
    ],
    "American Sour": [
      { rating: 3.5, comment: "Интересная кислотность с ягодными нотами. Необычно для пива." },
      { rating: 4.0, comment: "Люблю кислое пиво! Это один из лучших примеров американского саура." },
      { rating: 3.0, comment: "Для меня слишком кислый. Но понимаю, почему фанаты в восторге." },
    ],
    "Oatmeal Stout": [
      { rating: 4.5, comment: "Невероятно гладкий и кремовый! Овсянка делает текстуру просто роскошной." },
      { rating: 4.0, comment: "Кофе и шоколад с овсяной нежностью. Очень приятный стаут." },
      { rating: 4.0, comment: "Samuel Smith делает отличные классические британские эли. Этот — не исключение." },
      { rating: 4.5, comment: "Мой любимый овсяный стаут! Пьётся как шелковый кофейный напиток." },
    ],
    "Japanese Rice Lager": [
      { rating: 3.5, comment: "Чистый и сухой — идеально к суши. Рис делает его особенно лёгким." },
      { rating: 3.0, comment: "Обычный рисовый лагер. Ничего особенного, но со своей задачей справляется." },
      { rating: 3.5, comment: "Сашими + Саппоро = идеальная пара. Минеральный и освежающий." },
    ],
    "Baltic Porter": [
      { rating: 4.0, comment: "Мощный балтийский портер! Кофе, шоколад, карамель — всё как я люблю." },
      { rating: 4.5, comment: "Польские портеры — это отдельный вид искусства. Этот — отличный пример." },
      { rating: 3.5, comment: "Хороший портер, но хотелось бы чуть большей глубины вкуса." },
      { rating: 4.0, comment: "Тёмный, плотный, согревающий. Отличный выбор для холодного вечера." },
    ],
    "Japanese Dry Lager": [
      { rating: 3.5, comment: "Очень чистый и сухой профиль. Понимаю, почему японцы его так любят." },
      { rating: 3.0, comment: "Обычный лагер, но действительно очень сухой. К еде заходит отлично." },
      { rating: 3.5, comment: "Asahi Super Dry — правильно назван. Сухой как пустыня, но в хорошем смысле." },
    ],
    "Australian Pale Ale": [
      { rating: 3.5, comment: "Неплохой австралийский эль. Фруктовый и питкий, хорошо для жаркого дня." },
      { rating: 4.0, comment: "Coopers — классика Австралии! Нефильтрованный, с характером." },
      { rating: 3.5, comment: "Освежающий и ненавязчивый. Хорошая альтернатива обычным лагерам." },
    ],
    "Extra Stout": [
      { rating: 4.0, comment: "Плотный и насыщенный стаут! Кофе и шоколад на высоте." },
      { rating: 3.5, comment: "Австралийский экстра-стаут меня приятно удивил. Глубокий вкус." },
      { rating: 4.0, comment: "Отличный стаут для любителей тёмных сортов. Плотный и ароматный." },
    ],
    "Canadian Ale": [
      { rating: 3.5, comment: "Типичное канадское пиво. Ничего выдающегося, но стабильно." },
      { rating: 3.0, comment: "Molson Export — классика, но для меня слишком простой." },
      { rating: 3.5, comment: "Мягкий и питкий. Хорошо для вечернего отдыха после работы." },
    ],
    "Italian Pale Lager": [
      { rating: 3.0, comment: "Обычный итальянский лагер. К пицце подходит неплохо." },
      { rating: 3.5, comment: "Moretti — достойный представитель итальянского пивоварения. Пьётся легко." },
      { rating: 3.0, comment: "Ничего особенного, но со своей задачей справляется. Средний лагер." },
    ],
    "Ancient Ale": [
      { rating: 4.0, comment: "Совершенно необычный вкус! Имбирь и мирра создают восточный характер." },
      { rating: 3.5, comment: "Интересный эксперимент от Baladin. Экзотично, но не для каждого." },
      { rating: 4.0, comment: "Нора — пиво, которое расширяет горизонты. Медово-пряный букет." },
    ],
    "Spanish Pale Lager": [
      { rating: 3.5, comment: "Отличный каталонский лагер. С тапасом — просто песня!" },
      { rating: 3.0, comment: "Estrella Damm — попсовый, но качественный. В Барселоне пьёшь с удовольствием." },
      { rating: 3.5, comment: "Чистый и освежающий, как и должно быть испанское пиво." },
    ],
    "Catalan Lager": [
      { rating: 3.5, comment: "Мягкий и приятный каталонский лагер. Moritz — бренд с историей." },
      { rating: 3.5, comment: "Освежающий и питкий. Хорошая альтернатива масс-маркету в Испании." },
      { rating: 3.0, comment: "Неплохо, но для меня нет ничего выдающегося. Средний лагер." },
    ],
    "Brut IPA": [
      { rating: 4.0, comment: "Сухой как шампанское! Полностью меняет представление об IPA." },
      { rating: 3.5, comment: "Интересная концепция. Минеральный финиш и цитрусовые ноты." },
      { rating: 4.0, comment: "To Øl делает необычное пиво, и это — отличный пример. Брют-IPA — это новое!" },
    ],
    "American Barleywine": [
      { rating: 4.5, comment: "Мощный норвежский барливайн! Солод, хмель и тепло — шедевр." },
      { rating: 4.0, comment: "Нёгне Э делает мощное пиво, и #100 —-confirm это. Выдержка идёт ему на пользу." },
      { rating: 4.0, comment: "Плотный и сложный. Не для новичков, но ценители оценят." },
    ],
    "Rye IPA": [
      { rating: 4.0, comment: "Ржаной характер придаёт особую пряность. Отличный IPA от Lervig!" },
      { rating: 3.5, comment: "Рожь + хмель = интересная комбинация. Чуть острый финиш." },
      { rating: 4.0, comment: "Норвежцы делают отличные IPA. Этот — с характером!" },
    ],
    "Czech Dark Lager": [
      { rating: 3.5, comment: "Мягкий тёмный лагер. Шоколад и карамель без лишней горечи." },
      { rating: 4.0, comment: "Чешские тёмные лагеры — недооценённая категория! Этот — отличный." },
      { rating: 3.5, comment: "Пьётся легче, чем выглядит. Приятный обжаренный характер." },
    ],
    "Irish Red Ale": [
      { rating: 4.0, comment: "Тёплый и карамельный — именно то, что я ожидаю от ирландского красного эля!" },
      { rating: 3.5, comment: "Smithwick's — классика Ирландии. Мягкий и приятный." },
      { rating: 4.0, comment: "Карамельные и хлебные ноты в идеальном балансе. Люблю этот стиль!" },
    ],
    "French Witbier": [
      { rating: 3.5, comment: "Цитрусовый и лёгкий — хорошая альтернатива Хугардену." },
      { rating: 3.0, comment: "Kronenbourg Blanc — попсовый витбир. Ничего особенного, но освежает." },
      { rating: 3.5, comment: "Мутный, цитрусовый, с кориандром. Неплохо для летнего вечера." },
    ],
    "Bière de Garde": [
      { rating: 4.0, comment: "Французская бьер де гард — это скрытая жемчужина! Пряный и сложный." },
      { rating: 3.5, comment: "Jenlain Ambrée — отличный пример стиля. Карамель и пряности." },
      { rating: 4.0, comment: "Сложный и согревающий. Французы умеют делать пиво!" },
    ],
    "Argentine Pale Lager": [
      { rating: 3.0, comment: "Обычный аргентинский лагер. К асадо заходит идеально." },
      { rating: 2.5, comment: "Quilmes — не моё пиво. Но аргентинцы его обожают, и я уважаю." },
      { rating: 3.0, comment: "Простой и лёгкий. Свой народ знает, что ему нужно." },
    ],
    "New Zealand IPA": [
      { rating: 4.0, comment: "Новозеландский хмель — это что-то! Тропики и цитрусы на весь бокал." },
      { rating: 4.5, comment: "Epic Armageddon — мощный и ароматный. Один из лучших NZ IPA!" },
      { rating: 4.0, comment: "Garage Project делает безумно вкусное пиво. Этот IPA не исключение." },
    ],
    "Indian Pale Lager": [
      { rating: 3.0, comment: "Обычный индийский лагер. Лёгкий и ненавязчивый." },
      { rating: 3.0, comment: "Kingfisher — базовое пиво Индии. К карри заходит отлично." },
      { rating: 2.5, comment: "Ничего особенного. Но для индийского рынка — свой парень." },
    ],
    "Thai Lager": [
      { rating: 3.0, comment: "Лёгкий тайский лагер. К пад-тай — то, что нужно!" },
      { rating: 2.5, comment: "Chang — бюджетный вариант. Пьётся, но ничего особенного." },
      { rating: 3.0, comment: "Singha получше Чанга. Более выразительный вкус." },
    ],
    "Korean Pale Lager": [
      { rating: 3.0, comment: "Обычный корейский лагер. Лёгкий и освежающий." },
      { rating: 3.0, comment: "Hite — попсовый, но со своей задачей справляется. К корейскому ББQ!" },
      { rating: 3.5, comment: "Простой и чистый. Корейцы знают толк в лёгком пиве." },
    ],
    "Korean Wheat Ale": [
      { rating: 3.5, comment: "Неплохой корейский пшеничный. Мягкий и фруктовый." },
      { rating: 3.0, comment: "Kloud — интересная попытка сделать крафт в Корее. Неплохо для начала." },
      { rating: 3.5, comment: "Освежающий и питкий. Хорошая альтернатива обычным корейским лагерам." },
    ],
    "American IPA": [
      { rating: 4.5, comment: "Bell's Two Hearted — эталон американского IPA! Citra хмель — магия." },
      { rating: 4.0, comment: "Мощный хмелевой характер с цитрусово-хвойным профилем. Отличный IPA!" },
      { rating: 4.0, comment: "Лагунитас — надёжный IPA на каждый день. Хороший баланс." },
      { rating: 4.5, comment: "Sculpin — один из самых питких 7%-х IPA. Манго и апельсин!" },
    ],
    "Barrel-Aged Stout": [
      { rating: 5.0, comment: "BCS — это легенда! Ваниль, бурбон, шоколад — невероятный букет." },
      { rating: 4.5, comment: "KBS — один из лучших баррельных стаутов. Кофе и бурбон — идеальная пара!" },
      { rating: 4.5, comment: "Goose Island доказали, что баррельное пиво — это искусство." },
      { rating: 4.0, comment: "Мощный и сложный. 14.7% — не шутки, но пьётся как десерт." },
    ],
    "Imperial IPA": [
      { rating: 4.0, comment: "90 Minute IPA — инновационный подход! Непрерывное хмелеварение даёт результат." },
      { rating: 4.5, comment: "Dogfish Head делает пиво для гурманов. 9% и 90 IBU — мощно!" },
      { rating: 4.0, comment: "Сложный и мощный IIPA. Не для новичков, но любители оценят." },
    ],
    "American Porter": [
      { rating: 4.0, comment: "Отличный американский портер! Шоколад и кофе в красивом балансе." },
      { rating: 4.5, comment: "Deschutes Black Butte — классика! Один из лучших портеров в мире." },
      { rating: 3.5, comment: "Хороший портер, но мне хотелось чуть больше дымности." },
    ],
    "California Common": [
      { rating: 4.0, comment: "Anchor Steam — уникальный стиль! Ничего подобного больше нет в мире." },
      { rating: 3.5, comment: "Интересный вкус с карамельно-травянистыми нотами. Калифорнийская классика." },
      { rating: 4.0, comment: "Steam Beer — часть истории американского пивоварения. Уважаю!" },
    ],
    "Imperial Stout": [
      { rating: 5.0, comment: "Kentucky Brunch — мифическое пиво! Кофе, мёд, шоколад... шедевр." },
      { rating: 4.5, comment: "12% но пьётся как десерт. Топлинг Голиаф — магия!" },
      { rating: 4.5, comment: "Одно из лучших имперских стаутов. Сложный и невероятно вкусный." },
    ],
    "Doppelbock": [
      { rating: 4.5, comment: "Ayinger Celebrator — лучший доппельбок! Солодовый шедевр." },
      { rating: 4.0, comment: "Paulaner Salvator — оригинал стиля. Мощный и сладкий." },
      { rating: 4.0, comment: "Немецкие двойные боки — это любовь. Карамель и хлеб на высоте." },
      { rating: 4.5, comment: "Карамель, изюм, шоколад — всё что я люблю в одном бокале!" },
    ],
    "Weizenbock": [
      { rating: 4.5, comment: "Aventinus — легенда пшеничного пивоварения! Банан, гвоздика, изюм." },
      { rating: 4.0, comment: "Мощный и сложный пшеничный бок. Тёмные фрукты и специи." },
      { rating: 4.5, comment: "Schneider делает лучшие пшеничные пива. Aventinus — вершина!" },
    ],
    "Dunkelweizen": [
      { rating: 4.0, comment: "Тёмный вайсбир — отличная альтернатива обычному. Шоколад и банан!" },
      { rating: 3.5, comment: "Franziskaner Dunkel — мягкий и питкий. Хороший тёмный вайсбир." },
      { rating: 4.0, comment: "Банан и гвоздика с тёмной ноткой — интересная комбинация." },
    ],
    "Munich Dunkel": [
      { rating: 4.0, comment: "Отличный баварский дункель! Хлеб и карамель в чистом виде." },
      { rating: 3.5, comment: "Schönramer делает качественное пиво. Дункель не исключение." },
      { rating: 4.0, comment: "Мягкий и тёплый тёмный лагер. К Bavarian cuisine — идеально." },
    ],
    "Schwarzbier": [
      { rating: 4.0, comment: "Кёстритцер — классика чёрного лагера! Кофе и шоколад, но лёгкий." },
      { rating: 3.5, comment: "Чёрный цвет обманчив — пьётся легко. Тёмные ноты без тяжести." },
      { rating: 4.0, comment: "Один из моих любимых немецких стилей. Köstritzer — эталон!" },
    ],
    "Altbier": [
      { rating: 4.0, comment: "Uerige — лучший альтбир! Мощная горечь и солодовая база." },
      { rating: 4.5, comment: "Дюссельдорфская гордость! Топ-ферментация, но характер лагера." },
      { rating: 3.5, comment: "Хороший альтбир, но для меня слишком горький. Стиль такой." },
    ],
    "Berliner Weisse": [
      { rating: 3.5, comment: "Освежающая кислинка — идеально для лета! С сиропом вообще супер." },
      { rating: 4.0, comment: "Классический берлинер вайсе. Лёгкий, кислый, необычный." },
      { rating: 3.0, comment: "Для меня слишком кислый. Но с сиропом Waldmeister — другое дело." },
    ],
    "Gose": [
      { rating: 4.0, comment: "Гозе — самый недооценённый стиль! Кислый и солёный — идеально." },
      { rating: 3.5, comment: "Интересный вкус с солоноватостью. Освежает необычно." },
      { rating: 3.5, comment: "Göller делает достойную гозу. Кориандр и соль — интересная пара." },
    ],
    "Flanders Red Ale": [
      { rating: 4.5, comment: "Rodenbach Grand Cru — шедевр фламандского пивоварения! Кислый и сложный." },
      { rating: 4.0, comment: "Вишня, гранат, дуб — невероятный букет. Как красное вино, только пиво." },
      { rating: 4.5, comment: "Фландрийское бургундское! Это пиво для тех, кто любит сложные вкусы." },
    ],
    "Oud Bruin": [
      { rating: 3.5, comment: "Кисло-сладкий характер интересен. Liefmans делает хорошее oud bruin." },
      { rating: 4.0, comment: "Вишнёвые и сливовые ноты в кислом фоне. Неплохо!" },
      { rating: 3.5, comment: "Для любителей кислого пива — отличный выбор. Необычный и запоминающийся." },
    ],
    "Belgian Strong Golden Ale": [
      { rating: 4.5, comment: "Duvel — одно из величайших пив мира! 8.5% и не чувствуется." },
      { rating: 4.0, comment: "Delirium Tremens — красивая бутылка и хорошее пиво. Фруктовый и пряный." },
      { rating: 4.5, comment: "Сложный, элегантный, опасно питкий. Шедевр бельгийского пивоварения!" },
      { rating: 4.0, comment: "Золотой цвет, фруктовый аромат, сухой финиш. Классика Бельгии." },
    ],
    "Belgian Pale Ale": [
      { rating: 4.5, comment: "Orval — уникальное пиво! Бреттаноматис даёт фермерский характер." },
      { rating: 4.0, comment: "Сухой, хмелевой, сложный. Каждый раз раскрывается по-новому." },
      { rating: 4.5, comment: "Траппистское качество и уникальный характер. Люблю это пиво!" },
    ],
    "ESB": [
      { rating: 4.0, comment: "Fuller's ESB — классика английского пивоварения! Карамель и хмель." },
      { rating: 4.5, comment: "Один из лучших ESB в мире. Солодовый характер на высоте." },
      { rating: 3.5, comment: "Хороший английский биттер. Карамельные ноты и умеренная горечь." },
    ],
    "Scotch Wee Heavy": [
      { rating: 4.0, comment: "Belhaven Wee Heavy — шотландская классика! Карамель и лёгкий дымок." },
      { rating: 3.5, comment: "Тёплый и солодовый. Понимаю, почему шотландцы его любят." },
      { rating: 4.0, comment: "Мощный солодовый характер с торфяной ноткой. Отличный wee heavy!" },
    ],
    "English Bitter": [
      { rating: 4.0, comment: "Классический английский биттер! Именно так должен звучать этот стиль." },
      { rating: 3.5, comment: "Harvey's делает отличное пиво. Sussex Best — заслуженная репутация." },
      { rating: 4.0, comment: "Нежный солодовый вкус с фруктовыми нотами. Пабный идеал!" },
    ],
    "English Brown Ale": [
      { rating: 3.5, comment: "Newcastle Brown — классика Англии. Мягкий и карамельный." },
      { rating: 3.0, comment: "Для меня слишком простой. Но как масс-маркет — нормально." },
      { rating: 3.5, comment: "Ореховые и хлебные ноты в тёплом теле. Хорошо для вечера." },
    ],
    "Belgian Blond Ale": [
      { rating: 3.5, comment: "Affligem Blond — приятный бельгийский блонд. Фруктовый и мягкий." },
      { rating: 4.0, comment: "Грушевые и специй ноты. Пьётся легко для 6.8%. Хорошо!" },
      { rating: 3.5, comment: "Аббатское качество. Солодовый и фруктовый в хорошем балансе." },
    ],
  };

  const styleReviews = reviewsByStyle[style] || [
    { rating: 3.5, comment: "Неплохое пиво, стоит попробовать." },
    { rating: 4.0, comment: "Приятный вкус, буду покупать ещё." },
    { rating: 3.5, comment: "Нормально для своего стиля. Рекомендую попробовать." },
    { rating: 3.0, comment: "Ожидал большего, но в целом неплохо." },
  ];

  // Pick 3-5 reviews
  const count = 3 + Math.floor(Math.random() * 3); // 3-5
  const shuffled = [...styleReviews].sort(() => Math.random() - 0.5);
  const selected = shuffled.slice(0, count);

  // Shuffle authors
  const shuffledAuthors = [...reviewAuthors].sort(() => Math.random() - 0.5);

  return selected.map((review, i) => ({
    author: shuffledAuthors[i % shuffledAuthors.length],
    rating: review.rating,
    comment: review.comment,
  }));
}

const trendingData = [
  { beerName: "Pliny the Elder", category: "craft", rank: 1, checkinDelta: 340 },
  { beerName: "Hazy IPA", category: "craft", rank: 2, checkinDelta: 280 },
  { beerName: "Saison Dupont", category: "craft", rank: 3, checkinDelta: 195 },
  { beerName: "Guinness Draught", category: "macro", rank: 1, checkinDelta: 1200 },
  { beerName: "Heineken Lager", category: "macro", rank: 2, checkinDelta: 980 },
  { beerName: "Corona Extra", category: "macro", rank: 3, checkinDelta: 870 },
  { beerName: "Rochefort 10", category: "global", rank: 1, checkinDelta: 420 },
  { beerName: "Westmalle Tripel", category: "global", rank: 2, checkinDelta: 380 },
  { beerName: "Pilsner Urquell", category: "global", rank: 3, checkinDelta: 350 },
  { beerName: "Baltika 9", category: "weekly", rank: 1, checkinDelta: 560 },
  // New trending entries
  { beerName: "Bell's Two Hearted Ale", category: "craft", rank: 4, checkinDelta: 165 },
  { beerName: "Tree House Julius", category: "craft", rank: 5, checkinDelta: 145 },
  { beerName: "Goose Island Bourbon County Stout", category: "craft", rank: 6, checkinDelta: 130 },
  { beerName: "Estrella Damm", category: "macro", rank: 4, checkinDelta: 780 },
  { beerName: "Hite", category: "macro", rank: 5, checkinDelta: 620 },
  { beerName: "Chang", category: "macro", rank: 6, checkinDelta: 540 },
  { beerName: "Duvel", category: "global", rank: 4, checkinDelta: 310 },
  { beerName: "Nøgne Ø #100", category: "global", rank: 5, checkinDelta: 275 },
  { beerName: "Epic Armageddon IPA", category: "weekly", rank: 2, checkinDelta: 420 },
  { beerName: "Hitachino Nest White Ale", category: "weekly", rank: 3, checkinDelta: 380 },
];

async function main() {
  console.log("🌱 Seeding database...");

  // Clear existing data
  await prisma.review.deleteMany();
  await prisma.favorite.deleteMany();
  await prisma.trendingBeer.deleteMany();
  await prisma.searchHistory.deleteMany();
  await prisma.beer.deleteMany();

  console.log("📦 Creating beers...");

  // Create beers
  const createdBeers: Map<string, string> = new Map();

  for (const beer of correctedBeers) {
    const labelName = encodeBeerName(beer.name);
    const label = `https://placehold.co/300x400/78350F/FFF8E1?text=${labelName}`;

    const created = await prisma.beer.create({
      data: {
        name: beer.name,
        style: beer.style,
        abv: beer.abv,
        ibu: (beer as Record<string, unknown>).ibu as number,
        country: beer.country,
        brewery: beer.brewery,
        description: beer.description,
        label,
        rating: beer.rating,
        ratingCount: beer.ratingCount,
        untappdBid: Math.floor(Math.random() * 100000) + 10000,
        totalCheckins: beer.totalCheckins,
        monthlyCheckins: beer.monthlyCheckins,
        dailyCheckins: beer.dailyCheckins,
        source: "seed",
      },
    });

    createdBeers.set(beer.name, created.id);
    console.log(`  ✓ ${beer.name} (${beer.style})`);
  }

  console.log("💬 Creating reviews...");

  // Create reviews
  let totalReviews = 0;
  for (const beer of correctedBeers) {
    const beerId = createdBeers.get(beer.name);
    if (!beerId) continue;

    const reviews = generateReviews(beer.name, beer.style);

    for (const review of reviews) {
      await prisma.review.create({
        data: {
          beerId,
          author: review.author,
          rating: review.rating,
          comment: review.comment,
          createdAt: new Date(
            Date.now() - Math.floor(Math.random() * 90 * 24 * 60 * 60 * 1000)
          ),
        },
      });
      totalReviews++;
    }
  }
  console.log(`  ✓ Created ${totalReviews} reviews`);

  console.log("📈 Creating trending entries...");

  // Create trending entries
  for (const trending of trendingData) {
    const beerId = createdBeers.get(trending.beerName);
    if (!beerId) {
      console.log(`  ⚠ Beer "${trending.beerName}" not found for trending`);
      continue;
    }

    await prisma.trendingBeer.create({
      data: {
        beerId,
        category: trending.category,
        checkinDelta: trending.checkinDelta,
        rank: trending.rank,
      },
    });
    console.log(`  ✓ ${trending.beerName} → ${trending.category} #${trending.rank}`);
  }

  console.log("\n✅ Seeding complete!");
  console.log(`  🍺 Beers: ${correctedBeers.length}`);
  console.log(`  💬 Reviews: ${totalReviews}`);
  console.log(`  📈 Trending: ${trendingData.length}`);
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error("❌ Seeding failed:", e);
    await prisma.$disconnect();
    process.exit(1);
  });